import { chromium } from '@playwright/test';
import { readFile } from 'node:fs/promises';
const font = await readFile('frontend/assets/manrope-latin.woff2');
const browser = await chromium.launch();
const page = await browser.newPage({viewport:{width:1200,height:630},deviceScaleFactor:1});
await page.setContent(`<!doctype html><style>
@font-face{font-family:Manrope;src:url(data:font/woff2;base64,${font.toString('base64')})}*{box-sizing:border-box}body{margin:0;background:#f5f5ef;color:#232720;font-family:Manrope;padding:53px 66px}.brand{display:flex;gap:13px;align-items:center;font-size:25px;font-weight:750}.mark{display:flex;gap:4px;transform:skew(-14deg)}.mark i{display:block;width:7px;height:24px;background:#232720}.mark i:nth-child(2){height:32px;margin-top:-4px}.kicker{margin-top:74px;font-size:12px;letter-spacing:2px;font-weight:650;color:#69795a}h1{font-size:73px;line-height:1.13;letter-spacing:-4px;font-weight:650;margin:20px 0 25px}h1 span{color:#657e48}.copy{font-size:17px;color:#64715a;line-height:1.9;max-width:535px}.diagram{position:absolute;top:151px;right:66px;width:330px;border:1px solid #d3dbc6;border-radius:14px;padding:28px;background:#eef1e6;transform:rotate(2deg)}.node{border:1px solid #c5d1b4;background:#fbfcf6;padding:20px;font-size:16px;text-align:center;border-radius:8px;font-weight:650}.line{height:35px;width:1px;background:#9cb877;margin:auto}.standard{background:#d5f68b;padding:27px;font-size:32px;letter-spacing:-1px}.wallets{display:flex;gap:8px}.wallets div{flex:1;font-size:10px;background:#fbfcf6;border:1px solid #c5d1b4;padding:16px 5px;text-align:center;border-radius:6px}.bottom{position:absolute;left:66px;right:66px;bottom:40px;padding-top:21px;border-top:1px solid #d8dfcc;font-size:12px;color:#6a7b57;display:flex;justify-content:space-between}.pill{border:1px solid #bccba8;border-radius:4px;padding:7px 11px;font-size:10px;letter-spacing:1px;position:absolute;right:66px;top:54px}
</style><div class="brand"><div class="mark"><i></i><i></i><i></i></div>brc100.org</div><div class="pill">AN OPEN WALLET STANDARD</div><div class="kicker">THE INTERFACE BETWEEN APPS & WALLETS</div><h1>One interface.<br><span>An open world.</span></h1><div class="copy">Keys. Payments. Identity.<br>Build for the interface. Leave the choice to the user.</div><div class="diagram"><div class="node">Your application</div><div class="line"></div><div class="node standard">BRC-100</div><div class="line"></div><div class="wallets"><div>Desktop wallet</div><div>Browser wallet</div><div>User's choice</div></div></div><div class="bottom"><span>Explore the standard. Build something open.</span><span>brc100.org ↗</span></div>`);
await page.evaluate(() => document.fonts.ready);
await page.screenshot({path:'frontend/assets/social.png'});
await browser.close();
